# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  DC_DataCenter

steps:
- task: TerraformInstaller@1
  displayName: terraform installation
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: Initilizing terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DC_3Tier_Azure_Infra_WebApp/WebApp_Project'
    backendServiceArm: 'DC_WID_SC01'
    backendAzureRmStorageAccountName: 'dcindstoragea001'
    backendAzureRmContainerName: 'dcpipeline001'
    backendAzureRmKey: 'webappdc.tfstate'
- task: TerraformTask@5
  displayName: running terraform fmt
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DC_3Tier_Azure_Infra_WebApp/WebApp_Project'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'DC_WID_SC01'
- task: TerraformTask@5
  displayName: running terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DC_3Tier_Azure_Infra_WebApp/WebApp_Project'

- task: TerraformTask@5
  displayName: executing terraform plan for infra
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/DC_3Tier_Azure_Infra_WebApp/WebApp_Project'
    environmentServiceNameAzureRM: 'DC_WID_SC01'

